export const questions = [
  { text: "What’s my favorite weekend activity?", options: ["Sleeping", "Watching movies", "Gaming", "Going out"] },
  { text: "What’s my favorite drink?", options: ["Coffee", "Tea", "Juice", "Water"] },
  { text: "If I watch a movie, which genre would I pick?", options: ["Action", "Comedy", "Horror", "Sci-Fi"] },
  { text: "What’s my favorite snack?", options: ["Chocolate", "Chips", "Fruits", "Ice cream"] },
  { text: "Where do I feel most comfortable?", options: ["Home", "Cafe", "Park", "Beach"] },
  { text: "What’s my favorite color?", options: ["Red", "Blue", "Black", "Green"] },
  { text: "When am I most productive?", options: ["Morning", "Afternoon", "Evening", "Night"] },
  { text: "If I could travel, where would I go?", options: ["Mountains", "Beach", "City", "Countryside"] },
  { text: "What’s my go-to music genre?", options: ["Pop", "Rock", "Hip-hop", "Classical"] },
  { text: "How do I usually react under stress?", options: ["Stay calm", "Panic", "Overthink", "Ask for help"] },
  { text: "My favorite type of movie snack?", options: ["Popcorn", "Nachos", "Chocolate", "Ice cream"] },
  { text: "If I could learn a new skill, I’d choose?", options: ["Cooking", "Dancing", "Coding", "Photography"] },
  { text: "My ideal weekend morning looks like?", options: ["Sleeping in", "Jogging", "Gaming", "Reading"] },
  { text: "If I could hang out with friends, I’d prefer?", options: ["Movie night", "Outdoor adventure", "Gaming session", "Cafe chat"] },
  { text: "My favorite dessert?", options: ["Ice cream", "Cake", "Chocolate", "Fruit salad"] },
  { text: "If I could choose a pet, I’d pick?", options: ["Dog", "Cat", "Fish", "Bird"] },
  { text: "My favorite mode of transport?", options: ["Car", "Bike", "Walking", "Public transport"] },
  { text: "My favorite beverage when relaxing?", options: ["Coffee", "Tea", "Smoothie", "Water"] },
  { text: "If I go out for fun, I’d choose?", options: ["Amusement park", "Beach", "Hiking", "Movie"] },
  { text: "My favorite way to spend free time?", options: ["Gaming", "Reading", "Social media", "Exercising"] },
];
